# Generated by Django 4.1.1 on 2022-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='oi')),
                ('telefone', models.BigIntegerField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
