# Generated by Django 4.1.1 on 2022-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='telefone',
            field=models.BigIntegerField(null=True),
        ),
    ]
