# Generated by Django 4.1.1 on 2022-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_core_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Seu nome'),
        ),
    ]
