# Generated by Django 4.1.1 on 2022-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_core_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='core',
            name='telefone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
