# Generated by Django 4.1.1 on 2022-10-03 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_core_email_alter_core_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='titulo', max_length=50)),
                ('frase', models.CharField(default=' ', max_length=100)),
                ('nome_do_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('url_do_projeto', models.CharField(blank=True, max_length=50, null=True)),
                ('descrição', models.TextField(blank=True, max_length=5000, null=True)),
                ('depoimento_do_cliente', models.TextField(blank=True, max_length=5000, null=True)),
                ('imagem_do_cliente', models.FileField(default='default/images/depoimentos_imagem.png', upload_to='portfolio/images/')),
                ('capa_do_projeto', models.FileField(default='default/images/Em-Breve.jpg', upload_to='portfolio/images/')),
                ('data_de_criação', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='categoria', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='portfolio/images/')),
                ('add_imagem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.portfoliocategoria'),
        ),
    ]
