# Generated by Django 4.1.1 on 2022-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contato_contatoredesocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='email',
        ),
        migrations.RemoveField(
            model_name='core',
            name='telefone',
        ),
        migrations.AddField(
            model_name='core',
            name='profissao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='core',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
    ]
