# Generated by Django 4.1.1 on 2022-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_core_email_remove_core_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='data_de_criação',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
    ]
