# Generated by Django 4.1.1 on 2022-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_core_data_de_criação'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='Qual é o seu nome?', max_length=50, null=True)),
                ('profissão', models.CharField(blank=True, default='Qual é sua profissão?', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='Qual é o seu email?', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, default='Qual é o seu telefone?', max_length=11, null=True)),
                ('hero', models.FileField(default='default/images/hero.webp', upload_to='sobre/images/')),
                ('foto_de_perfil', models.FileField(default='default/images/foto_de_perfil.svg', upload_to='sobre/images/')),
                ('background_depoimento', models.FileField(default='default/images/backgroud.webp', upload_to='sobre/images/')),
                ('frase', models.CharField(default='Qual é a sua frase?', max_length=50)),
                ('data_de_criação', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
            ],
        ),
    ]
