# Generated by Django 4.1.1 on 2022-10-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sobre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobre',
            name='background_depoimento',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='hero',
        ),
    ]
