# Generated by Django 4.1.1 on 2022-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_sobre_background_depoimento_remove_sobre_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobre',
            name='resumo',
            field=models.CharField(blank=True, default='Fale um pouco sobre você.', max_length=5000, null=True),
        ),
    ]
