# Generated by Django 4.1.1 on 2022-10-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sobre_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobre',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='telefone',
        ),
    ]
