# Generated by Django 4.1.1 on 2022-10-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_sobre_email_remove_sobre_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.CharField(blank=True, max_length=11, null=True)),
                ('data_de_criação', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.portfoliocategoria')),
            ],
        ),
    ]
