# Generated by Django 4.1.1 on 2022-10-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
    ]
