# Generated by Django 4.1.1 on 2022-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_servicos_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='nome',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
