# Generated by Django 4.1.1 on 2022-10-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_servico_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDeContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(max_length=5000)),
                ('data_de_criação', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
            ],
        ),
    ]
