# Generated by Django 4.1.1 on 2022-10-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_formulariodecontato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='core',
        ),
    ]
