# Generated by Django 4.1.1 on 2022-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodecontato',
            name='email',
            field=models.EmailField(max_length=600),
        ),
    ]
